FROM openjdk:17-jdk-slim

MAINTAINER eazybytes

COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

# Execute this command on cmd line
ENTRYPOINT ["java", "-jar", "accounts-0.0.1-SNAPSHOT.jar"]