build:
  version: v2.0

accounts:
  message: "Welcome to Eazybank accounts related local APIs"
  contactDetails:
    name: "John Doe - Developper"
    emails: "john@eazybank.com"
  onCallSupport:
    - (555)555-1234
    - (555)523-1365
