build:
  version: v4.0

loans:
  message: "Welcome to Eazybank Loans related default APIs"
  contactDetails:
    name: "Jill Baker - default Lead"
    emails: "jill@eazybank.com"
  onCallSupport:
    - (111)526-1234
    - (222)786-1365
